# Generated by Django 3.0.5 on 2020-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='blogtopic',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogcontent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Blogitems',
        ),
    ]
