# Generated by Django 3.0.6 on 2020-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200430_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
